version: "3"
services:
  api:
    image: marcosreuquen/fast-api
    ports:
      - 80:8000
    env_file:
      - ./.env
    environment:
      - DB_URL=${DB_URL}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
